name: Upload AEM Package Workflow

on:
  workflow_call:

jobs:
  upload-package:
    runs-on: rhel888
    steps:
      - name: Upload AEM package
        env:
          AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
          AEM_PACKAGE_NAME: ${{ env.AEM_PACKAGE_NAME }}
          AEM_HOST: ${{ env.AEM_HOST }}
        run: |
          curl -u $AEM_CREDENTIALS \
            -F cmd=upload \
            -F force=true \
            -F package=@$AEM_PACKAGE_NAME \
            http://$AEM_HOST/crx/packmgr/service/.json
