name: Upload AEM Package Workflow

on:
  workflow_call:
    inputs:
      AEM_CREDENTIALS:
        required: true
        type: string
      AEM_PACKAGE_NAME:
        required: true
        type: string
      AEM_HOST:
        required: true
        type: string

jobs:
  upload-package:
    runs-on: rhel999
    steps:
      - name: Print environment variables
        run: env

      - name: Check AEM service availability
        run: curl -u admin:admin http://localhost:4502

      - name: List directory contents
        run: ls -l

      - name: Upload AEM package
        env:
          AEM_CREDENTIALS: ${{ inputs.AEM_CREDENTIALS }}
          AEM_PACKAGE_NAME: ${{ inputs.AEM_PACKAGE_NAME }}
          AEM_HOST: ${{ inputs.AEM_HOST }}
        run: |
          IFS=',' read -r -a HOSTS <<< "${AEM_HOST}"
          for host in "${HOSTS[@]}"; do
            echo "Deploying to $host"
            curl -u $AEM_CREDENTIALS \
              -F cmd=upload \
              -F force=true \
              -F package=@${AEM_PACKAGE_NAME} \
              --connect-timeout 10 \
              "$host/crx/packmgr/service/.json"
          done
