name: AEM Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      awsAccount:
        description: 'AWS Account (e.g., eng, test, prod, localhost)'
        required: true
        default: 'localhost'

jobs:
 
  Upload-Package:
    runs-on: aem
    steps:
      
      - name: Upload AEM package (conditional)
        env:
          AEM_HOST: ${{ env.AEM_HOST }}
          AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
          AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip"
        run: |
          curl -u $AEM_CREDENTIALS \
            -F cmd=upload \
            -F force=true \
            -F package=@$AEM_PACKAGE_NAME \
            http://$AEM_HOST:4502/crx/packmgr/service/.json
