name: AEM Deployment Workflow

on:
  repository_dispatch:
    types: [deploy-environment]

jobs:
  Checkout-Repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq and jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Extract Environment URL
        id: extract_url
        run: |
          environment=${{ github.event.client_payload.environment }}
          url=$(yq e ".environments[] | select(has(\"$environment\")) | .\"$environment\"" environments.yaml)
          if [ -z "$url" ]; then
            echo "Invalid environment: $environment"
            exit 1
          fi
          echo "AEM_HOST=$url" >> $GITHUB_ENV

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: we.retail.community.apps-1.11.84.zip

  Upload-Package:
    runs-on: aem2
    needs: Checkout-Repository
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: .

      - name: Upload AEM package (conditional)
        env:
          AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
          AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip"
          AEM_HOST: ${{ env.AEM_HOST }}
        run: |
          curl -u $AEM_CREDENTIALS \
            -F cmd=upload \
            -F force=true \
            -F package=@$AEM_PACKAGE_NAME \
            http://$AEM_HOST/crx/packmgr/service/.json
