name: Upload AEM Package Workflow

on:
  workflow_call:
     inputs:
      AEM_CREDENTIALS:
        required: true
        type: string
      AEM_PACKAGE_NAME:
        required: true
        type: string
      AEM_HOST:
        required: true
        type: string



jobs:
  upload-package:
    runs-on: rhel999
    steps:
      - name: Upload AEM package
        env:
          AEM_CREDENTIALS: ${{ inputs.AEM_CREDENTIALS }}
          AEM_PACKAGE_NAME: ${{ inputs.AEM_PACKAGE_NAME }}
          AEM_HOST: ${{ inputs.AEM_HOST }}
        run: |
          curl -u -v admin:admin \
            -F cmd=upload \
            -F force=true \
            -F package=@we.retail.community.apps-1.11.84.zip \
            http://localhost:4502/crx/packmgr/service/.json
